services:
  postgres_db_service:
    container_name: postgres_db_serv
    image: postgres:14
    ports:
      - "8082:5432"
    hostname: postgres_db_serv
    environment:
      - POSTGRES_PASSWORD=local
      - POSTGRES_USER=local
      - POSTGRES_DB=flyway-test-db